name: Wheel-ManyLinux-3.8

on: [workflow_dispatch]

jobs:
  build_wheels:
    strategy:
      matrix:
        platform:
          - [ubuntu-20.04, manylinux_x86_64]
        python: ["cp38"]

    name: Build wheel for ${{ matrix.python }}-${{ matrix.platform[0] }}-${{ matrix.platform[1] }}
    runs-on: ${{ matrix.platform[0] }}

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-python@v2  # Used to host cibuildwheel
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel~=2.14.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_PRERELEASE_PYTHONS: True
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.platform[1] }}
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_BUILD_VERBOSITY: 3
          CIBW_ENVIRONMENT: WHEEL=1

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
