name: Wheel

on: [workflow_dispatch]

jobs:
  build_wheels:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10]
        python: ["cp311", "cp310", "cp39", "cp38", "cp37"]
        
    name: Build wheel for ${{ matrix.python }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-python@v2  # Used to host cibuildwheel
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel~=2.0.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_PRERELEASE_PYTHONS: True
          CIBW_BUILD: ${{ matrix.python }}-*
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_BUILD_VERBOSITY: 3
          CIBW_ENVIRONMENT: WHEEL=1

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
